modLoader = "javafml" #mandatory
loaderVersion = "${loader_version_range}"
logoFile="logo.png"
license = "${mod_license}"
[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "gtceu"
mandatory = true
versionRange = "[7.1.0,7.2.0)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "ldlib"
mandatory = true
versionRange = "[1.0.40.b,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "configuration"
mandatory = true
versionRange = "[2.2.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "kubejs"
mandatory = false
versionRange = "[2001.6.5-build.14,)"
ordering = "AFTER"
side = "BOTH"