#KubeJS Dev Properties
#Fri Aug 22 13:02:42 EEST 2025
logSkippedTags=false
logSkippedRecipes=false
logSkippedPlugins=true
debugInfo=true
strictTags=false
logAddedRecipes=false
logRemovedRecipes=false
logModifiedRecipes=false
logInvalidRecipeHandlers=true
dataPackOutput=false
logGeneratedData=false
logErroringRecipes=true
alwaysCaptureErrors=false
